# Multiple Controller Configuration Example
# Demonstrates using AFG alongside other Nav2 controllers

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    odom_topic: "odom"
    
    # Multiple controller plugins
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["AFGFollowPath", "PreciseFollowPath", "RotateInPlace"]
    
    # Progress checker
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    
    # Goal checker
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true
    
    # AFG for high-speed outdoor navigation
    AFGFollowPath:
      plugin: "afg_controller::AFGController"
      desired_linear_vel: 1.0
      max_angular_vel: 1.5
      convergence_gain: 2.0
      flow_gain: 3.0
      boundary_layer: 0.15
      lookahead_distance: 1.0
      transform_tolerance: 0.1
      max_robot_pose_search_dist: 15.0
    
    # AFG for precise indoor navigation
    PreciseFollowPath:
      plugin: "afg_controller::AFGController"
      desired_linear_vel: 0.3
      max_angular_vel: 0.8
      convergence_gain: 3.0
      flow_gain: 1.5
      boundary_layer: 0.05
      lookahead_distance: 0.3
      transform_tolerance: 0.1
      max_robot_pose_search_dist: 5.0
    
    # Rotation controller for precise orientation
    RotateInPlace:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "AFGFollowPath"
      angular_dist_threshold: 0.785  # 45 degrees
      forward_sampling_distance: 0.5
      rotate_to_heading_angular_vel: 1.0
      max_angular_accel: 3.2
      simulate_ahead_time: 1.0
